### ISSUE TITLE
Screenshot thread

### ISSUE THREAD

**Issue by creatrice** [MLstate/PEPS#1]
![Messages View](https://cloud.githubusercontent.com/assets/817369/5923743/09105572-a656-11e4-9305-eb2a2bc578ce.png)

![Dashboard View](https://cloud.githubusercontent.com/assets/817369/5923753/1a5dfd20-a656-11e4-959f-f19d9df12c0e.png)

![Files View](https://cloud.githubusercontent.com/assets/817369/5923759/2596cc3a-a656-11e4-8397-b9296a39001c.png)

**Comment by hbbio** [comment]
![screen shot 2015-02-17 at 11 45 21](https://cloud.githubusercontent.com/assets/808274/6226992/c51135b2-b69a-11e4-9211-bfe4d855afc0.png)

**Comment by creatrice** [comment]
![peps-bulk-import-view](https://cloud.githubusercontent.com/assets/817369/6227219/16b3e62e-b69d-11e4-875c-3ec07ba9094d.png)

![peps-users-view-001](https://cloud.githubusercontent.com/assets/817369/6227038/2e865c98-b69b-11e4-9d2a-5dc33df4b53d.png)

**Comment by creatrice** [comment]
Files
![screen shot 2015-04-01 at 12 11 48](https://cloud.githubusercontent.com/assets/817369/6938997/78c117be-d868-11e4-9a68-d26847fcf8ee.png)
