### ISSUE TITLE
Classes in admin dashboard doesn't click well

### ISSUE THREAD

**Issue by KillianKemps** [MLstate/PEPS#11]
In the admin dashboard, the Classes tab. I had to click really on the text of the tags to open them. It does not work on the button.

![pepsclasses_annotations](https://cloud.githubusercontent.com/assets/6884630/6320512/8948e89a-bad7-11e4-862f-66e293328ba8.png)

**Comment by KillianKemps** [comment]
It discovered the same issue in the contact page. I understand that every page with this layout is concerned.

**Comment by creatrice** [comment]
Thanks for the user feedback.
This behaviour was useful in certain cases then we had multiple links on the same list-group-item.
We will make a patch and set the link on the whole element for classes and users lists.
