### ISSUE TITLE
Cannot Access PEPS using domain

### ISSUE THREAD

**Issue by tikaPahadi** [MLstate/PEPS#18]
After installing PEPS and do ***make run***,
I get the following message:
***....
Now open your browser and log in to https://localhost
At first launch, you will set up your admin password***

But, when I point to http://my-ip it points to my ***var/www/html***
And, when I point to https://my-ip it says ***Webpage Not Available***

I am using Ubuntu 14.04 on DigitalOcean

**Comment by houndbee** [comment]
I have the same issue. Any pointers to get it working?

**Comment by tikaPahadi** [comment]
No, I have contacted the developers. I don't understand why they have not been able to figure out for more than a week.

**Comment by hbbio** [comment]
Because we are unable to reproduce. And /var/www is not set by PEPS!

**Comment by hbbio** [comment]
What are the contents of:

docker ps -a

docker logs peps_server

**Comment by tikaPahadi** [comment]
**docker ps -a => all fine except PEPS Server**

d2c8a63a5ec4        peps:latest         "/sbin/my_init"        About a minute ago   Exited (1) About a minute ago                                              peps_server

**docker logs peps_server**
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10peps.sh...
*1 modules are missing. Please run: sudo npm install -g opabsl.opp*
*** /etc/my_init.d/10peps.sh failed with status 1

*** Killing all processes...


`And is there a preference where should PEPS be cloned? Right now, I am on the base directory `

**Comment by HenriChataing** [comment]
Hello, could you give me temporary access to the machine ?

**Comment by tikaPahadi** [comment]
Henri, Check your email. I have the credentials for you

**Comment by HenriChataing** [comment]
Hi, I just checked your server, and the error eludes me for now.
I will be having a longer look tomorrow morning.

**Comment by tikaPahadi** [comment]
Umm, Any solutions seems to be ahead? What about the installation of Opalang?

**Comment by hbbio** [comment]
Your server instance is too small.
You need 2G RAM minimum to run PEPS.

**Comment by casinelli26** [comment]
How were you able to resolve this problem? I am running into the same issue.
