### ISSUE TITLE
Unable to acess peps_server on a non standard port

### ISSUE THREAD

**Issue by croydondias** [MLstate/PEPS#24]
I change the HTTPS_PORT to 9091 in the makefile. Verified that the container was running on the port.

Getting SSL errors when accessing the port though
```
croydon@vps138520:~/PEPS$ curl -vk https://localhost:9091
* Rebuilt URL to: https://localhost:9091/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9091 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to localhost:9091 
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to localhost:9091 
```

Have created a detailed issue on it here:
http://stackoverflow.com/questions/32130496/access-a-docker-container-on-a-non-standard-ssl-port

**Comment by hbbio** [comment]
Thanks for the report. We will look at the issue. 

Note that allowing HTTP connections to PEPS behind a reverse proxy is a one-line change in PEPS.

**Comment by croydondias** [comment]
Oh really?
Please tell me how to do that. I thought PEPS forced HTTPS thoughout.

**Comment by croydondias** [comment]
Issue resolved - http://stackoverflow.com/a/32171597/458493

**Comment by hbbio** [comment]
Sorry for the delay, add the `--no-ssl` option to PEPS launch script.
