### ISSUE TITLE
Confirmation email link error from peps.in

### ISSUE THREAD

**Issue by cryptowest** [MLstate/PEPS#26]
After creating an account on peps.in, a confirmation email is sent:

>Thanks for registering an account for PEPS. Please click on the link below to confirm your email address.
>http://keygen.mlstate.com:8080/validate/username/123456

The link 404s but changing the port to 80 or erasing it works.

**Comment by hbbio** [comment]
Thanks for the report.
The URL in the generated emails was not updated, it should have been fixed.

Correct domain is now: `https://register.peps.in/`.
