### ISSUE TITLE
without docker?

### ISSUE THREAD

**Issue by AndrinS** [MLstate/PEPS#28]
Is there a way to install it without docker?

**Comment by hbbio** [comment]
Yes, you can build Peps from source. The repository is MLstate/PEPS-source.

**Comment by AndrinS** [comment]
Hey hbbio

I'm new to this.. This is my fist linux VM I'm working on..

I'd be very thankful if you could give me a few advices how to do it.

cheers

**Comment by AndrinS** [comment]
May I ask again?

**Comment by hbbio** [comment]
Hi Andrin.
As I told you, the repository is [here](https://github.com/MLstate/peps-source). Please follow the instructions there and or issue there.
