### ISSUE TITLE
Does PEPS support spam filtering?

### ISSUE THREAD

**Issue by guiguan** [MLstate/PEPS#37]
Hi MLstate,

Any support for incoming spam filtering via spamassassin, spf and dkim?

Regards,
Guan

**Comment by hbbio** [comment]
Haraka has built in spam filtering. Look at Haraka configuration and if you have a good configuration, feel free to submit a pull request.

**Comment by guiguan** [comment]
@hbbio Thank you for your reply. That's very nice. Wel will use PEPs in our up coming project. :)

**Comment by itsazzad** [comment]
Where is the `SPAM` folder?
