### ISSUE TITLE
Search and Encryption, how do they work together ?

### ISSUE THREAD

**Issue by changwuf31** [MLstate/PEPS#42]
Would you be willing to elaborate more on the concept on how these two things work together. I assume that the indexes on solr are not encrypted, yes ?

**Comment by hbbio** [comment]
Exactly.
Messages and files which are encrypted are currently not indexed.
It is feasible to add search to encrypted data but it is costly in terms of performance and bandwidth so we decided to save the feature for later.

**Comment by changwuf31** [comment]
Ic, thank you @hbbio for the explanation :+1:
