### ISSUE TITLE
LDAP IMAP integration

### ISSUE THREAD

**Issue by xbgmsharp** [MLstate/PEPS#7]
Hello,

On the webpage you say:
"PEPS est compatible avec les protocoles standards des messageries et annuaires : LDAP, SMTP, IMAP."

I could not find any settings in the WebGUI to have LDAP and IMAP integration.
If this limited to a pay edition?

**Comment by hbbio** [comment]
The description you mention comes out from our company website, where we package other products with PEPS to provide customized solutions for our customers. Feel free to [contact us](mailto:contact@mlstate.com) for inquiries.
